name: Run Discord Bot

on:
  push:
    branches: [ main ]

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the bot
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      run: |
        echo "DISCORD_TOKEN=$DISCORD_TOKEN" > .env
        python bot.py

    - name: Decode YouTube cookies
      run: |
        echo "$YOUTUBE_COOKIES_B64" | base64 -d > cookies.txt
       env:
        YOUTUBE_COOKIES_B64: ${{ secrets.YOUTUBE_COOKIES_B64 }}

